language: rust

sudo: required

dist: trusty

install:
  - curl https://static.rust-lang.org/rustup.sh |
    sh -s -- --add-target=$TARGET --disable-sudo -y --prefix=`rustc --print sysroot`

script:
  - cargo build
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
      sh ci/run-docker.sh $TARGET;
    else
      export CARGO_TARGET_DIR=`pwd`/target;
      sh ci/run.sh $TARGET;
    fi

cache: cargo

matrix:
  include:

    # Test compatibility
    #
    # 1.9.0 is the oldest supported version of Rust. This value should NOT be
    # changed without prior discussion.
    #
    # This build also deploys docs
    - os: linux
      rust: 1.9.0
      script:
        # Ensure that the build works without default features
        - cargo build --no-default-features
        - cargo test
        - cargo doc --no-deps
      install:

    # Test on latest stable
    - os: linux
      rust: stable
      script:
        # Ensure that the build works without default features
        - cargo build --no-default-features
        - cargo test
      install:

    # OS X
    - os: osx
      rust: stable
      script:
        # Ensure that the build works without default features
        - cargo build --no-default-features
        - cargo test
      install:

    # iOS
    - os: osx
      osx_image: xcode8.2
      env: TARGET=x86_64-apple-ios
      rust: stable

    # Android
    - os: linux
      env: TARGET=arm-linux-androideabi
      rust: stable

notifications:
  email:
    on_success: never

# Deploy documentation to S3 for specific branches. At some
# point, it would be nice to also support building docs for
# a specific tag
deploy:
  provider: s3
  access_key_id: AKIAISVZFP2MDUU6KA5A
  secret_access_key:
    secure: DsarqYqQzaRus/1m4k4aa9tF+ciVN28UKIYap91EK34KYZmyKslG7O+tSNEqfQV3zq4iO6OLh8s2Gzs+sA0f+OSbDcsL9F5uZcvRVwejgvP91zsHPUzmi6Rb6AlIqnwGE/PQ7vUYxJWrRlNKe6ZUAH5w20h5yRUybZKQIS99PoQ=
  bucket: rust-doc
  skip_cleanup: true
  local-dir: target/doc
  upload-dir: mio/${TRAVIS_BRANCH}
  acl: public_read
  on:
    condition: $TRAVIS_RUST_VERSION == "1.9.0" && $TRAVIS_OS_NAME == "linux"
    repo: carllerche/mio
    branch:
      - master
